services:
  - type: web
    name: police-rag-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 -m gunicorn api:app --bind 0.0.0.0:10000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10